AllCops:
  RunRailsCops: true
  Exclude:
      - 'db/**/*'
      - 'config/**/*'
      - 'script/**/*'
      - 'bin/**/*'
      - 'lib/tasks/cucumber.rake'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false
