development:
  adapter: postgresql
  encoding: unicode
  database: peluquerias_development
  template: template0
  pool: 5
  username: jenny
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: peluquerias_test
  template: template0
  pool: 5
  username: jenny
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: peluquerias_production
  pool: 5
  username: jenny
  password:
