development:
  adapter: postgresql
  encoding: unicode
  database: peluquerias_development
  pool: 5
  username: jenny
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: peluquerias_test
  pool: 5
  username: jenny
  password:
